# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Bootloader configuration. The bootloader is installed to allow
# the system to start (and pick one of the installed operating
# systems to run).
#
# Take note that Debian-derivatives that use unmodified GRUB EFI packages
# should specifically set *efiBootloaderId* to "debian" because that is
# hard-coded in `grubx64.efi`.
---
# Variable from packagechooser that determines which bootloader to use
efiBootLoaderVar: "packagechooser_bootloader"

# grub / systemd-boot
# Use GRUB as default bootloader (more compatible)
efiBootLoader: "grub"

# GRUB configuration
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"

# Kernel parameters
kernelParams: [ "quiet" ]

efiBootloaderId: "genesi"

installEFIFallback: true
