# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# sets pacman options for package handling.
---

backend: pacman
skip_if_no_internet: false
update_db: false
update_system: false

pacman:
    num_retries: 3
    disable_download_timeout: true
    needed_only: true
    # Force overwrite to prevent conflicts with genesi-settings
    overwrite: "*"
